# Generated by Django 3.2 on 2021-04-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('price', models.DecimalField(decimal_places=4, max_digits=15, null=True, verbose_name='price')),
                ('link', models.CharField(max_length=255, null=True, verbose_name='link')),
                ('speed', models.IntegerField(null=True, verbose_name='speed')),
                ('pay_period', models.IntegerField(null=True, verbose_name='pay_period')),
                ('tarif_group_id', models.IntegerField(null=True, verbose_name='tarif_group_id')),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=12, null=True, verbose_name='login')),
                ('name_last', models.CharField(max_length=255, null=True, verbose_name='name_last')),
                ('name_first', models.CharField(max_length=255, null=True, verbose_name='name_first')),
            ],
        ),
        migrations.CreateModel(
            name='servers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payday', models.DateField(verbose_name='payday')),
                ('tarif_nom', models.ManyToManyField(null=True, to='Zapros.tarif', verbose_name='Тариф')),
                ('user_nom', models.ManyToManyField(null=True, to='Zapros.users', verbose_name='Пользователь')),
            ],
        ),
    ]
